### ISSUE TITLE
from balance import balanced_accuracy, balanced_categorical_accuracy

### ISSUE THREAD

**Issue by XIXIYOUNG2018** [Nanotekton/drugability#2]
**when i run this code:" from balance import balanced_accuracy, balanced_categorical_accuracy"
there emerge such error:**
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'balance'

After pip install balance, a new error appear as follow:
from balance import balanced_accuracy, balanced_categorical_accuracy

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: cannot import name 'balanced_accuracy'

Is there a mode named as balance or any version requirement of balance?

**Comment by Nanotekton** [comment]
Sorry, forgot to put a script in the repo. Corrected.
Keep in mind that it requires `imblearn` package.
